// ------------------------------ POKEMONS CRUD -----------------------------------------
### GET all pokemons

GET http://localhost:8080/api/pokemons

### GET one pokemon by id

GET http://localhost:8080/api/pokemons/5aad8e0f-4d81-406f-b024-6f7d311e3a82

### PUT new pokemon

PUT http://localhost:8080/api/pokemons/245b3ff3-2ce3-4887-98ff-9f3b35269440
Content-Type: application/json

{
  "name": "NOWY POKEMON",
  "level": 120,
  "trainer": "71b687a3-0569-40c3-a999-46f19c68980c"
}


### UPDATE leve in pokemon by id

PATCH http://localhost:8080/api/pokemons/245b3ff3-2ce3-4887-98ff-9f3b35269440
Content-Type: application/json

{
  "level": 68
}

### DELETE one pokemon by id

DELETE http://localhost:8080/api/pokemons/4fcb1c92-6717-494e-b6fb-089d4e6215df


// ------------------------------ TRAINER CRUD -----------------------------------------
### GET all trainers

GET http://localhost:8080/api/trainers

### GET one trainer by id

GET http://localhost:8080/api/trainers/3b25be7c-a2ba-4240-8723-969fb130fa22

### PUT new trainer

PUT http://localhost:8080/api/trainers/71b687a3-0569-40c3-a999-46f19c68980c
Content-Type: application/json

{
  "name": "new_Hubert_trainer",
  "age": 12
}

### UPDATE name trainer

PATCH http://localhost:8080/api/trainers/71b687a3-0569-40c3-a999-46f19c68980c
Content-Type: application/json

{
  "name": "Kaczynski"
}

### DELETE one trainer by id

DELETE http://localhost:8080/api/trainers/71b687a3-0569-40c3-a999-46f19c68980c


