// ------------------------------ POKEMONS CRUD -----------------------------------------
### GET all pokemons

GET http://localhost:8081/api/pokemons

### GET one pokemon by id

GET http://localhost:8081/api/pokemons/59168623-900a-4d40-bdc6-d5675a395e49

### GET all pokemons by Trainer

GET http://localhost:8081/api/trainers/3b25be7c-a2ba-4240-8723-969fb130fa22/pokemons


### PUT new pokemon

PUT http://localhost:8081/api/pokemons/245b3ff3-2ce3-4887-98ff-9f3b35269440
Content-Type: application/json

{
  "name": "NOWY POKEMON",
  "level": 120,
  "trainer": "71b687a3-0569-40c3-a999-46f19c68980c"
}

### UPDATE leve in pokemon by id

PATCH http://localhost:8081/api/pokemons/4810f048-7e5f-4d00-aa3c-55e53f414785
Content-Type: application/json

{
  "level": 68
}

### DELETE one pokemon by id

DELETE http://localhost:8081/api/pokemons/4fcb1c92-6717-494e-b6fb-089d4e6215df
